package com.wnt.ireport.model;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.util.Locale;

import javax.swing.JPanel;

import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/*
 * 重写JasperViewer类，目的是修改报表标题
 */
public class JasperSubViewer extends  javax.swing.JFrame {

	private static final long serialVersionUID = 10200L;
	protected JRsubViewer viewer;
	private boolean isExitOnClose;
	private JPanel pnlMain;


	public JasperSubViewer(JasperPrint jasperPrint, boolean isExitOnClose,
			Locale locale, String title) {

		if (locale != null) {
			setLocale(locale);
		}
		this.isExitOnClose = isExitOnClose;

		initComponents(title);

		this.viewer = new JRsubViewer(jasperPrint, locale,title);
		this.pnlMain.add(this.viewer, BorderLayout.CENTER);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents(String title) {// GEN-BEGIN:initComponents
		pnlMain = new javax.swing.JPanel();

		setTitle(title);
		setIconImage(new javax.swing.ImageIcon(getClass().getResource(
				"/net/sf/jasperreports/view/images/jricon.GIF")).getImage());
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm();
			}
		});

		pnlMain.setLayout(new java.awt.BorderLayout());

		getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

		pack();

		Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
		java.awt.Dimension screenSize = toolkit.getScreenSize();
		
		int screenResolution = toolkit.getScreenResolution();
		float zoom = ((float) screenResolution) / JRViewer.REPORT_RESOLUTION;

		//int height = (int) (550 * zoom);
		//if (height > screenSize.getHeight()) {
		int	height = (int) screenSize.getHeight()-30;
		//}
		//int width = (int) (750 * zoom);
		//if (width > screenSize.getWidth()) {
		int	width = (int) screenSize.getWidth();
		//}

		java.awt.Dimension dimension = new java.awt.Dimension(width, height);
		setSize(dimension);
		setLocation(0,0);
	}// GEN-END:initComponents

	/** Exit the Application */
	void exitForm() {// GEN-FIRST:event_exitForm

		if (this.isExitOnClose) {
			System.exit(0);
		} else {
			this.setVisible(false);
			this.viewer.clear();
			this.viewer = null;
			this.getContentPane().removeAll();
			this.dispose();
		}

	}// GEN-LAST:event_exitForm

	/**
	 *
	 */
	public void setZoomRatio(float zoomRatio)
	{
		viewer.setZoomRatio(zoomRatio);
	}


	/**
	 *
	 */
	public void setFitWidthZoomRatio()
	{
		viewer.setFitWidthZoomRatio();
	}

	/**
	 *
	 */
	public void setFitPageZoomRatio()
	{
		viewer.setFitPageZoomRatio();
	}
	public static void viewReport(JasperPrint jasperPrint, boolean isExitOnClose,String title) {
		viewReport(jasperPrint, isExitOnClose, null,title);
	}

	public static void viewReport(JasperPrint jasperPrint,
			boolean isExitOnClose, Locale locale, String title) {
		JasperSubViewer jasperSubViewer = new JasperSubViewer(jasperPrint,
				isExitOnClose, locale, title);
		jasperSubViewer.setVisible(true);
	}

}
